name: Deploy to github pages
on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest
      
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: setup node.js
        uses: actions/setup-node@v4
        with:
          node-version: '16'

      - name: Install Dependencies
        run: npm install || true

      - name: Build project
        run: npm run build || true

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5 
        with:
          branch: gh-pages
          folder: . 
